name: solar-system
on:
 push:
    branches:
        - main
        - feature/*
jobs:
    unit-testing:
        name: unit testing
        runs-on: ubuntu-latest
        steps:
        -  name: checkout repo
           uses: actions/checkout@v4

        - name: setup nodejs
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: install depedencies
          run: npm install

        - name: unit testing
          run: npm test